import type { Metadata } from "next";
import { Geist, Geist_Mono, Lusitana } from "next/font/google";
import { Analytics } from "@vercel/analytics/react"
import "./globals.css";
import localFont from 'next/font/local'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lusitana = Lusitana({
  weight: ['400', '700'],
  subsets: ["latin"],
  variable: "--font-lusitana",
});

// Add your custom font
const customFont = localFont({
  src: '../../public/fonts/Lordish-Regular.ttf',
  variable: '--font-custom',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${customFont.variable} ${lusitana.variable} font-custom antialiased`}
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
